<style>
    h1,
    h2,
    h3 {
        text-align: center;
    }

    p {
        color: #fff;
    }
</style>
<?php
session_start();

if (isset($_SESSION['COMPANYID'])) {
    $companyid = $_SESSION['COMPANYID'];
} else {
    header('location: ../../index.php');
}
date_default_timezone_set('Asia/Manila');

$today = date("Y-m-d H:i:s");
$logs = mysqli_query($conn, "INSERT INTO tbl_log (NAME, LOG_TIME, ROLE, ACTIVITY) VALUE ('{$_SESSION['USER_NAME']}', '$today', '{$_SESSION['ROLE']}', 'Generate Report')");

function generateRow()
{

    $contents = '';
    require_once "../../../connection/config.php";
    // $job = $_GET['jobname'] ?? null;

    $print_emp = "SELECT tbljobregistration.*, tbljobregistration.REGISTRATIONID as regid, tbljobregistration.APPLICANTID as appid, DATE_FORMAT(tbljobregistration.REGISTRATION_DATE, '%M %e, %Y') AS date, tbljobregistration.STATUS as jobstat, tbldecision.*,
 tbljob.* FROM tbljobregistration, tbldecision, tbljob WHERE tbldecision.DECISIONID = 
tbljobregistration.DECISIONID AND tbljobregistration.JOBID = tbljob.JOBID AND tbljobregistration.companyid = '{$_SESSION['COMPANYID']}' AND tbldecision.PERCENTAGE < 50 AND tbljobregistration.STATUS = 'Pending' 
AND tbljobregistration.REGISTRATION_DATE > DATE_SUB(now(), INTERVAL 6 MONTH) ORDER BY tbldecision.PERCENTAGE DESC, tbldecision.VERIFY_LEVEL DESC";

    //use for MySQLi OOP
    $query = $conn->query($print_emp);
    while ($row = $query->fetch_assoc()) {
        $email_company = $row['EMAIL'];
        $name_conpamy = $row['USERNAME'];
        $contents .= "
            <tr>
                                            <td>" . $row['APPLICANT'] . "</td>
                                            <td>" . $row['date'] . "</td>
                                            <td>" . $row['OCCUPATION_TITLE'] . "</td>
                                        </tr>
			";
    }

    return $contents;
}

require_once('../tcpdf/tcpdf.php');

$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Nicola Asuni');
$pdf->SetTitle('Employee');
$pdf->SetSubject('TCPDF Tutorial');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, 'Accurafind' . '', $_SESSION['COMPANY_NAME']);

// set header and footer fonts
$pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__) . '/lang/eng.php')) {
    require_once(dirname(__FILE__) . '/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// ---------------------------------------------------------

// set font
$pdf->SetFont('helvetica', 'B', 20);

// add a page
$pdf->AddPage();

$pdf->Write(0, 'List of Not Qualified Applicant', '', 0, 'L', true, 0, false, false, 0);

$pdf->SetFont('helvetica', '', 8);




$content = '';
$content .= '
      	<table border="1" cellspacing="0" cellpadding="10">  
           <tr>  
           <th ><strong>APPLICANT NAME</strong></th>
            <th><strong>APPLY DATE</strong></th>
            <th><strong>APPLY POSITION</strong></th>
            
           </tr>  
      ';
$content .= generateRow();
$content .= '</table>';
$today = date('F j Y,');
$month = date('F');
$pdf->Write(5, 'Report generated in month of ' . $month, '', 0, 'L', true, 0, false, false, 0);

$pdf->writeHTML($content);

$pdf->Write(5, '' . $today, '', 0, 'R', true, 0, false, false, 0);
$pdf->Write(10, 'Generated by: ' . $_SESSION['USER_NAME'], '', 0, 'R', true, 0, false, false, 0);

$pdf->SetFont('helvetica', '', 8);

ob_end_clean();
$pdf->Output('members.pdf', 'I');
